// import { Inter } from 'next/font/google';
import "./globals.css";
import Providers from './providers'

// const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ru"
      /*className={`${inter.variable} h-full antialiased`}*/
    >
      <body className="min-h-full flex flex-col">
         <Providers>       {/*layout серверный компонент*/}
          {children}   {/* не напрямую вставляем провайдер redux в layout */}
        </Providers>  {/* создаем отделный клиентский провайдерс, там оборачиваем редакс и уже потом его вставляем */}
        </body>
    </html>
  );
}
